version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - sed -e '/^boto/d' -i requirements.txt
  build:
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo "python run.py -v ${ARG}"
      - python run.py -v $ARG
