version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - sed -e '/^boto/d' -i requirements.txt
  build:
    commands:
      - apt-get update
      - apt-get install -y libpq-dev postgresql-client-common postgresql-client-11
      - pip install -r requirements.txt
  post_build:
    commands:
      - python -m scripts.update -v --dia
